
### success case
POST {{host}}/oauth/token HTTP/1.1
Content-Type: application/json

{
  "grant_type": "authorization_code",
  "client_id": "qvpoDniytlVpPRYkbP4O/R80LebUdUB9", 
  "redirect_uri": "https://localhost:3000/test/callback",
  "code": "i~kEVCEUEvOiF3SPPv1QlWq6zUcXjoEX"
}



### success case
POST {{host}}/oauth/token HTTP/1.1
Content-Type: application/json

{
  "grant_type": "authorization_code",
  "client_id": "qvpoDniytlVpPRYkbP4O/R80LebUdUB9",
  "redirect_uri": "http://www.twinkle-i-nara.com/auth.do",
  "code": "JIug~RMJtpaiwuuBUGKtStKzirJUb1j6"
}