
### success case
POST {{host}}/oauth/token HTTP/1.1
Content-Type: application/json

{
  "grant_type": "authorization_code",
  "client_id": "qvpoDniytlVpPRYkbP4O/R80LebUdUB9",
  "redirect_uri": "https://google.com",
  "code": "I84dtnn-WSxu6P0TQMnmkn3dcpDSpOod"
}