
### success case
POST {{host}}/signIn HTTP/1.1
Content-Type: application/json
passport: JSZQNzk~dFbeN27micVxgODbT9igXak~M-tjsbp4W8bsF7N3XdC4sz13QMDeMdpi

{
  "email": "rick-1@test.com",
  "password": "test1234"
}

# https://localhost:3000/signin/U2FsdGVkX19Mh%2Fosqu4%2FZcj8IbSNmuqlF%2FtGyBlgpOBluPzVRNDivhcsC%2B%2FYmlaexw9zDaQYrG6uvS31SaIHJPmgQUvkiZU%2B0Ct38n1PvGWbvZpNWESTBGNfWcVmjZ6O%2F6p0RoIwhesNArxTmfhL4aNNAPSHJ47SFnj3OHNj300vZ2x4OxEzkT87uGijC8CEFh6ov4uzymBjwMqYU1G0RZFEC2v1%2BfZcgmv5oRCKpZ8Hgqnxc14f%2Fsu7cq51tTlk
# https://system-idp-auth.dev.iscreamarts.com/signin/?provider=101