
### success case
POST {{host}}/signIn HTTP/1.1
Content-Type: application/json
passport: 9u_MSSOdaDaOSNSt2GiLqev6gzckTKrv~lX4tz3zjYi.tjLrELFZEqlUx~jhauQS

{
  "email": "rick-2@test.com",
  "password": "test1234"
}

# https://localhost:3000/signin/U2FsdGVkX1%2FgpoxdNRnvvpiT%2FyWw5CsZ5xYwfAPTH5TeweoxOEsulTyiyfIWdi9xHgw47dThIhfYP%2FBP9r3i87j9Glh%2BJgHmePlwmP3zKbfXPc%2FOuYdY4r8mkPBn76IUehfU8KnrnlfNI6WofTlSYnYT2QVHB3gl8x4lC8czCIk57merpXPULOcrgPMyy%2B2kDHtiG1SnZ87DGD5Vc4pSEwpx9mNxzqi1nioza%2BXz%2BCdNrJ0S%2B9P50%2F%2F9hGGh0UVQ
# https://system-idp-auth.dev.iscreamarts.com/signin/?provider=101