### success case - children
GET {{host}}/child/token
Authorization: Bearer U2FsdGVkX1/aeieW236z0IrLbO2e8x+rmHzx3v/aIZ4D92zNZ7M8UCLZBMpMlFB1BY6RAacO8TcZ428CufFBvzfi2sETZW2pPQDOpQNpWEhYWCJ8jdi/kA0NPt8yo1fkswGEBcKr5OjxX4QMedPix2nvNWPslui8i0M3XCAiv4gVdfMhsDH/xbNeh7X/O4yL


### success case - child
GET {{host}}/child/token/5000000000000018
Authorization: Bearer U2FsdGVkX1/aeieW236z0IrLbO2e8x+rmHzx3v/aIZ4D92zNZ7M8UCLZBMpMlFB1BY6RAacO8TcZ428CufFBvzfi2sETZW2pPQDOpQNpWEhYWCJ8jdi/kA0NPt8yo1fkswGEBcKr5OjxX4QMedPix2nvNWPslui8i0M3XCAiv4gVdfMhsDH/xbNeh7X/O4yL