
### success case
PATCH  {{host}}/child/token/5000000000000020 HTTP/1.1
Content-Type: application/json
Authorization: Bearer U2FsdGVkX1/aeieW236z0IrLbO2e8x+rmHzx3v/aIZ4D92zNZ7M8UCLZBMpMlFB1BY6RAacO8TcZ428CufFBvzfi2sETZW2pPQDOpQNpWEhYWCJ8jdi/kA0NPt8yo1fkswGEBcKr5OjxX4QMedPix2nvNWPslui8i0M3XCAiv4gVdfMhsDH/xbNeh7X/O4yL

{
  "name": "아들1 - 수정",
  "birthDay": "2010-01-01",
  "gender": "GENDER.FEMALE"
}