
### success case
DELETE  {{host}}/child/token/5000000000000009 HTTP/1.1
Content-Type: application/json
Authorization: Bearer U2FsdGVkX1/XrJLwobQuBa6hphZhJwFHDMZeEExg8r9IBme1ddSZcD895vgPIjmKqtp6ZdTniP+6K+ZnBS5BohlZBQkvGfjQqoO0A+R/IOwVfCw1u+n2Tia2NAe5G17jzZqmTXvkCY7Q2jBC1YeYcAiZViOXgyumcVOmfM856OKdMx4ArxfDm4ETIad5tvBi
