### success case - children
GET {{host}}/child/token
Authorization: Bearer U2FsdGVkX18JWTrHEqKPZKFsBV1zMVPHwWFR1Hk1jW2lfjdrxwV+ujTtr0XxnXsOUoKTD7vnAI/ZQHN38wYvM/1gsoKjuUIQvQDEKleCl1drYNoAzO6RyMtR2IRdA2fxh4MT97H5hBDtxJJ7Bz5oA5WYW3RN9ksYaJ02CmeNyYoMLHj3CIqBk7eO8igV/rD8


### success case - child
GET {{host}}/child/token/5000000000000007
Authorization: Bearer U2FsdGVkX18JWTrHEqKPZKFsBV1zMVPHwWFR1Hk1jW2lfjdrxwV+ujTtr0XxnXsOUoKTD7vnAI/ZQHN38wYvM/1gsoKjuUIQvQDEKleCl1drYNoAzO6RyMtR2IRdA2fxh4MT97H5hBDtxJJ7Bz5oA5WYW3RN9ksYaJ02CmeNyYoMLHj3CIqBk7eO8igV/rD8