
### success case
POST {{host}}/signUp/rx HTTP/1.1
Content-Type: application/json

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick-07",
    "password": "test1234",
    "email": "rick-07@test.com"
  }
}


### success case with passport
POST {{host}}/signUp HTTP/1.1
Content-Type: application/json

{
  "passport": "iwR2C0v_UZCUD5YztBnL.zYd02aaNhA9OQtjaI13nHNo74hUgJrf9_qauiuhohw_",
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick-08",
    "password": "test1234",
    "email": "rick-08@test.com"
  }
}


### success case with memberProviderKey
POST {{host}}/signUp HTTP/1.1
Content-Type: application/json

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 301,
    "memberProviderKey": "301.1234567890",
    "name": "rick",
    "password": "test1234",
    "email": "rick-11@test.com"
  }
}


### success case with memberProviderKey and passport
POST {{host}}/signUp HTTP/1.1
Content-Type: application/json

{
  "passport": "TRgEpEg5MzQKzmDhrP.wsA0VQDQAJlZjusg66HfgjSaqT-YI9o4JSnt~shRu.I6C",
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 301,
    "memberProviderKey": "301.1234567890",
    "name": "rick-12",
    "password": "test1234",
    "email": "rick-12@test.com"
  }
}