
### success case with passport
POST {{host}}/signUp HTTP/1.1
Content-Type: application/json
passport: ~Bi4zzMF_KoYYPGMT-QKry7F~q-GG.9nKvllx7H03zl-yi77TaapyHUmHr.fGe3z

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick-11",
    "password": "test1234",
    "email": "rick-11@test.com"
  }
}


### success case with memberProviderKey
POST {{host}}/signUp HTTP/1.1
Content-Type: application/json
passport: 2d-S4.eV88n~jwoI0pNR2gPA8MHsVlQWH2XW5OkPwsN2LZVSo-d_TZgabUaoN23o

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 301,
    "memberProviderKey": "301.1234567890",
    "name": "rick",
    "password": "test1234",
    "email": "rick-11@test.com"
  }
}


### success case with memberProviderKey and passport
POST {{host}}/signUp HTTP/1.1
Content-Type: application/json
passport: 2d-S4.eV88n~jwoI0pNR2gPA8MHsVlQWH2XW5OkPwsN2LZVSo-d_TZgabUaoN23o

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": true
  },
  "memberDetail": {
    "providerId": 402,
    "memberProviderKey": "402.000367.c3a7962c4cf14b6fb0c6499acdbd3ef4.0426",
    "name": "Rick%20Bonglae",
    "password": "402.000367.c3a7962c4cf14b6fb0c6499acdbd3ef4.0426",
    "email": "j6j2tr8cd2@privaterelay.appleid.com"
  }
}