
### success case
GET {{host}}/oauth/authorize
  ?client_id=qvpoDniytlVpPRYkbP4O/R80LebUdUB9
  &redirect_uri=https://localhost:3000/test/callback
  &response_type=code
  &scope=id_token name email phone child
  &state=sldfk3gfy534F

# https://localhost:3000/signin/provider/apple?passport=
# https://system-idp-auth.dev.iscreamarts.com/signin/provider/apple?passport=