
### success case
POST {{host}}/member/withdrawal HTTP/1.1
Content-Type: application/json
Cookie: U2FsdGVkX1%2B5lkzvDTHdfpeHCPSlbEUKTTD0ANcyk%2FmSoSpk2nYdJH6YMGl1CgIfl4RQYMGE0GBQ%2B%2BwYb1GYqw0u%2B8A1qnI7wHTgzuQumadd0Cpn8fRXDDV12kCglG1t

{
  "withdrawalReason": "WITHDRAWAL.CONTENTS",
  "reasonExplanation": "이용할 만한 컨텐츠가 없었습니다."
}