
### success case
POST {{host}}/member/withdrawal HTTP/1.1
Content-Type: application/json
Cookie: iScreamArts-IDP=U2FsdGVkX1%2Bmm%2Ftv0gMrPwHhVXapTNc5Vj4ZtCiriR%2BIX%2BO96Yot4hRmQ5A8%2FC0p%2BzLnF%2B79AFMvLjSIfZF6XgEAbDhrh7RUCH03PTRV00GFfpRglTfow2SwNSAGt2s7

{
  "withdrawalReason": "WITHDRAWAL.CONTENTS",
  "reasonExplanation": "이용할 만한 컨텐츠가 없었습니다."
}