
### success case
POST {{host}}/signUp/phone HTTP/1.1
Content-Type: application/json
passport: 2c7xS-ZJaNUoTX_1CKFX47W1DrCQ-df3P8xxr.leWhd3.EWwXFJR0-sJ5GqEYQ_r

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick",
    "password": "test1234",
    "email": "rick-004@test.com"
  },
  "memberPhone": {
    "countryCallingCode": "82",
    "phoneNumber": "01012359879"
  }
}


### success case with passport
POST {{host}}/signUp/phone HTTP/1.1
Content-Type: application/json
passport: 2c7xS-ZJaNUoTX_1CKFX47W1DrCQ-df3P8xxr.leWhd3.EWwXFJR0-sJ5GqEYQ_r

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick-103",
    "password": "test1234",
    "email": "rick-103@test.com"
  },
  "memberPhone": {
    "countryCallingCode": "82",
    "phoneNumber": "01012349879"
  }
}

6

### success case with memberProviderKey
POST {{host}}/signUp/phone HTTP/1.1
Content-Type: application/json
passport: 2c7xS-ZJaNUoTX_1CKFX47W1DrCQ-df3P8xxr.leWhd3.EWwXFJR0-sJ5GqEYQ_r

{
  "member": {
    "isConsentedTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedMarketingUseAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 301,
    "memberProviderKey": "301.4273393725",
    "name": "%EA%B9%80%EB%B4%89%EB%9E%98",
    "password": "301.4273393725",
    "email": "rick.kim@daum.net"
  },
  "memberPhone": {
    "countryCallingCode": "82",
    "phoneNumber": "1044471414"
  }
}