
### success case
POST {{host}}/signUp/phone HTTP/1.1
Content-Type: application/json
passport: hsLt.LuI2-4oCN3evm9uqW8bQfwm7LjpLIWFwNiVHGVMIyG_fJ9XVIKAoH~ucuj3

{
  "member": {
    "isConsentedArtBonbonTermsAndConditions": true,
    "isConsentedILandTermsAndConditions": true,
    "isConsentedGalleryBonbonTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedUseAiSketchService": true,
    "isConsentedOver14Years": true,
    "isConsentedEventAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick-11",
    "password": "test1234",
    "email": "rick-11@test.com"
  },
  "memberPhone": {
    "countryCallingCode": "82",
    "phoneNumber": "01088880011"
  }
}


### success case
POST {{host}}/signUp/phone HTTP/1.1
Content-Type: application/json
passport: nbunmg6Z8mEiuIprP6u_-9Yi9GKkDTcAuV9o3ZAeczASHmrhm0xLuAp23hH81d04

{
  "member": {
    "isConsentedArtBonbonTermsAndConditions": true,
    "isConsentedILandTermsAndConditions": true,
    "isConsentedGalleryBonbonTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedUseAiSketchService": true,
    "isConsentedOver14Years": true,
    "isConsentedEventAndInformationReceiving": true
  },
  "memberDetail": {
    "providerId": 101,
    "name": "rick-001",
    "password": "test1234",
    "email": "rick-001@test.com"
  },
  "memberPhone": {
    "countryCallingCode": "82",
    "phoneNumber": "01011110001"
  }
}


### success case with memberProviderKey
POST {{host}}/signUp/phone HTTP/1.1
Content-Type: application/json
passport: ZHp-8Fet1sLQjH_UES-Rl2nyJD4qbGQj5~O9ONo87nDE4CBMXWc6.EYQhez7ziH1

{
  "member": {
    "isConsentedArtBonbonTermsAndConditions": true,
    "isConsentedILandTermsAndConditions": true,
    "isConsentedGalleryBonbonTermsAndConditions": true,
    "isConsentedCollectionAndUsePersonalData": true,
    "isConsentedUseAiSketchService": true,
    "isConsentedOver14Years": true,
    "isConsentedEventAndInformationReceiving": false
  },
  "memberDetail": {
    "providerId": 301,
    "memberProviderKey": "301.4273393725",
    "name": "%EA%B9%80%EB%B4%89%EB%9E%98",
    "email": "rick.kim@daum.net"
  },
  "memberPhone": {
    "countryCallingCode": "82",
    "phoneNumber": "1044471412"
  }
}