
### success case
PATCH {{host}}/verification/reset/password HTTP/1.1
Content-Type: application/json
passport: aeO36WEEs~jxzqBHp-3JbQDrIPttMGf1TxrqPqUvs9PkjvObqQtShoe_1G3mEK7O

{
  "token": "Rnyy1uwpLMmUmQxH",
  "password": "12345678"
}