### verify phone
GET {{host}}/verification/phone
  ?countryCallingCode=82
  &phoneNumber=01011110002
  &isWillVerifyDuplication=true
passport: NxqWS0uWv5KKej-Zsy7-H0J6YluGkJ7.YkHjkpsFf1E1yX-5zjN.6i9vI1yjwMP-


### get phone code
GET {{host}}/verification/phone/get
  ?countryCallingCode=82
  &phoneNumber=010-4447-1412
passport: qNAXQe6PCUyiT5PL~UnwM_UXIFFor81FvqO7LsHaYox6~ojTDToG.dIRGd1qdgT9