### verify phone
GET {{host}}/verification/phone
  ?countryCallingCode=82
  &phoneNumber=010-4447-1412
passport: qNAXQe6PCUyiT5PL~UnwM_UXIFFor81FvqO7LsHaYox6~ojTDToG.dIRGd1qdgT9

### get phone code
GET {{host}}/verification/phone/get
  ?countryCallingCode=82
  &phoneNumber=010-4447-1412
passport: qNAXQe6PCUyiT5PL~UnwM_UXIFFor81FvqO7LsHaYox6~ojTDToG.dIRGd1qdgT9