### verify phone
GET {{host}}/verification/phone
  ?countryCallingCode=82
  &phoneNumber=01044471412
  &isWillVerifyDuplication=false
passport: iX9nG.qE6EDZ_8dRzaQVnp964JlwAWcIK3gHXIlhwpmXU505VG7p48oEauiSTgp5


### get phone code
GET {{host}}/verification/phone/get
  ?countryCallingCode=82
  &phoneNumber=010-4447-1412
passport: iX9nG.qE6EDZ_8dRzaQVnp964JlwAWcIK3gHXIlhwpmXU505VG7p48oEauiSTgp5
