### verify email code
GET {{host}}/verification/phone/code
  ?countryCallingCode=82
  &phoneNumber=01044471412
  &verificationCode=486429
passport: 2d-S4.eV88n~jwoI0pNR2gPA8MHsVlQWH2XW5OkPwsN2LZVSo-d_TZgabUaoN23o
