### verify email code
GET {{host}}/verification/phone/code
  ?countryCallingCode=82
  &phoneNumber=01044471412
  &verificationCode=351289
passport: Iv1RQHS_E8jTXH0xD0bW9ZDrYm7QfJ0IzEysH6wzxlAwOtJD.H-XfGGZSr9M7rpV
